# Welcome to Jekyll!
# Custom Jekyll project Structure
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
author:
  - name: Guillermo Remache
    email: guillermo@justthingsido
    url: resume.justthingsido.com


# Site settings

title: Jekyll Template
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
keywords: ['some list, here ']

baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site
twitter_username: GRemache93
github_username:  justthingsido
linkedin_username: gremache
facebook: 'username'

# used to eliminate the need to add .html at the of of the URL
permalink: pretty

#- uncomment ga if you are using Google Analytics (replace 'UA-70296153' with your own)
# ga: UA-70296123-1
#- uncomment for fbAppId (Replace '733223316...' with you own)
# fbAppId: 733223385287067

# Build settings
markdown: kramdown

gems:
#   - octopress-minify-html
  - jekyll-gallery-generator
  - jekyll-sitemap


exclude: [node_modules, gulpfile.js, package.json, 'assets/css/main.sass']


# gallery Generator

gallery:
  # path to the gallery
  dir: gallery
  # title for gallery index
  title: "Gallery"
  # title prefix for gallery page. title=title_prefix+gallery_name
  title_prefix: ""
  # field to control sorting of galleries for the index page
  # (possible values are: title, date_time, best_image)
  sort_field: "date_time"
  # sizes for thumbnails
  thumbnail_size:
    x: 400
    y: 400
  # custom configuration for individual gallery
  # best_image is image for the index page (defaults to last image)
  galleries:
    # name of directory
    gratisography:
      # image to be used as thumbnails in index page
      best_image: best_image.jpg
